version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-pythonapp
hooks:
  BeforeInstall:
    - location: cleanup.sh
      timeout: 300
      runas: ubuntu  # Ensure this user has appropriate permissions
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: ubuntu
  AfterAllowTraffic:
    - location: scripts/restart_gunicorn.sh
      timeout: 60
      runas: root
