version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-pythonapp
hooks:
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: ubuntu
