version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-pythonapp
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/restart_gunicorn.sh
      timeout: 300
      runas: ubuntu

